apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: registration-service
  name: registration-service
spec:
  ports:
    - name: "10000"
      port: 10000
      targetPort: 10000
  selector:
    io.kompose.service: registration-service
status:
  loadBalancer: {}
