apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: registration-db
  name: registration-db
spec:
  ports:
    - name: "3308"
      port: 3308
      targetPort: 3308
  selector:
    io.kompose.service: registration-db
status:
  loadBalancer: {}
