apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: registration-db
  name: registration-db
spec:
  containers:
    - env:
        - name: MYSQL_DATABASE
          value: registration_db
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: env
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: env
        - name: MYSQL_TCP_PORT
          value: "3308"
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: env
        - name: SQL_INTERNAL_PORT
          value: "3308"
      image: mysql:latest
      name: registration-db
      ports:
        - containerPort: 3308
      resources: {}
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: registration-db
  restartPolicy: OnFailure
  volumes:
    - name: registration-db
      persistentVolumeClaim:
        claimName: registration-db
status: {}
