apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
  labels:
    app: react-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        backend: "true"
        app: react-ui
    spec:
      containers:
      - env:
            - name: REACT_APP_API_URL
              value: http://192.168.59.104:32000
        name: react-ui
        image: mattpdev/react-ui
        imagePullPolicy: Always
        name: react-ui
        ports:
          - name: http
            containerPort: 3000
      restartPolicy: Always
