apiVersion: v1
kind: Service 
metadata:
  labels:
    app: react-ui
  name: react-ui
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: react-ui 
