apiVersion: v1
kind: Service
metadata:
  labels:
    app: zuul-api
  name: zuul-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      nodePort: 32000
  selector:
    app: zuul-api
