apiVersion: apps/v1          
kind: Deployment              
metadata:
  name: kafka   
  labels:                    
    app: kafka
spec:
  replicas: 1                 
  selector:
    matchLabels:              
      app: kafka
  template:                   
    metadata:
      labels:                
        app: kafka
    spec:                     
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
          - name: http
            containerPort: 9092 
        env:                  
        - name: KAFKA_ADVERTISED_HOST_NAME 
          value: kafka-service
        # - name: KAFKA_LISTENERS
        #   value: PLAINTEXT://0.0.0.0:30092
        # - name: KAFKA_ADVERTISED_LISTENERS
        #   value: PLAINTEXT://kafka-service:30092
        # - name: KAFKA_ADVERTISED_PORT
        #   value: '30092'
        - name: KAFKA_ZOOKEEPER_CONNECT 
          value: zookeeper:2181 
        - name: KAFKA_BROKER_ID 
          value: '1'
        - name: KAFKA_CREATE_TOPICS
          value: 'registration:1:1'
---
apiVersion: v1                
kind: Service                 
metadata:                     
  name: kafka-service   
  labels:                     
    app: kafka-service
spec:
  selector:
    app: kafka  # The service exposes Pods with label `app=kafka`
  ports:                
  - name: kafka-port
    port: 9092
    targetPort: 9092