apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 32100
  selector:
    app: discovery-service
