apiVersion: v1
kind: Pod
metadata:
  labels:
    backend: "true"
    app: discovery-service
  name: discovery-service
spec:
  containers:
    - env:
        - name: eureka.client.fetch-registry
          value: "false"
        - name: eureka.client.register-with-eureka
          value: "false"
        - name: eureka.client.service-url.defaultZone
          value: http://192.168.59.100:8761/eureka/
      image: mattpdev/discovery-service
      name: discovery-service
      ports:
        - containerPort: 8761
  restartPolicy: OnFailure
