apiVersion: v1
kind: Service 
metadata:
  labels:
    app: angular-ui
  name: angular-ui
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      targetPort: 4200
      nodePort: 30002
  selector:
    app: react-ui
